// Generated by tools/build_sprites.py. Do not edit by hand.
export const SPRITES = {
  "angely": {
    "file": "assets/runtime/angely.webp",
    "frameWidth": 313,
    "frameHeight": 263,
    "originX": 0.5781,
    "originY": 0.9848,
    "bodyHeight": 243,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 243
      },
      "walk": {
        "start": 4,
        "end": 11,
        "fps": 12,
        "repeat": -1,
        "h": 237
      },
      "run": {
        "start": 12,
        "end": 19,
        "fps": 14,
        "repeat": -1,
        "h": 206
      },
      "start": {
        "start": 20,
        "end": 22,
        "fps": 18,
        "repeat": 0,
        "h": 248
      },
      "stop": {
        "start": 23,
        "end": 25,
        "fps": 14,
        "repeat": 0,
        "h": 243
      },
      "jump": {
        "start": 26,
        "end": 29,
        "fps": 20,
        "repeat": 0,
        "h": 232
      },
      "air": {
        "start": 30,
        "end": 30,
        "fps": 1,
        "repeat": -1,
        "h": 220
      },
      "fall": {
        "start": 31,
        "end": 32,
        "fps": 6,
        "repeat": -1,
        "h": 246
      },
      "land": {
        "start": 33,
        "end": 33,
        "fps": 1,
        "repeat": 0,
        "h": 208
      },
      "hurt": {
        "start": 34,
        "end": 35,
        "fps": 10,
        "repeat": 0,
        "h": 204
      },
      "celebrate": {
        "start": 36,
        "end": 39,
        "fps": 7,
        "repeat": -1,
        "h": 222
      },
      "defeat": {
        "start": 40,
        "end": 42,
        "fps": 5,
        "repeat": 0,
        "h": 180
      },
      "push": {
        "start": 43,
        "end": 48,
        "fps": 9,
        "repeat": -1,
        "h": 220
      }
    }
  },
  "angely_bow": {
    "file": "assets/runtime/angely_bow.webp",
    "frameWidth": 224,
    "frameHeight": 222,
    "originX": 0.3886,
    "originY": 0.982,
    "bodyHeight": 214,
    "anims": {
      "shoot": {
        "start": 0,
        "end": 4,
        "fps": 18,
        "repeat": 0,
        "h": 210
      }
    }
  },
  "angely_hammer": {
    "file": "assets/runtime/angely_hammer.webp",
    "frameWidth": 241,
    "frameHeight": 285,
    "originX": 0.6999,
    "originY": 0.986,
    "bodyHeight": 277,
    "anims": {
      "smash": {
        "start": 0,
        "end": 4,
        "fps": 12,
        "repeat": 0,
        "h": 267
      }
    }
  },
  "umbra": {
    "file": "assets/runtime/umbra.webp",
    "frameWidth": 320,
    "frameHeight": 320,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 312,
    "anims": {
      "idle": {
        "start": 0,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 309
      },
      "cast": {
        "start": 8,
        "end": 14,
        "fps": 10,
        "repeat": 0,
        "h": 288
      },
      "hurt": {
        "start": 15,
        "end": 18,
        "fps": 10,
        "repeat": 0,
        "h": 250
      },
      "dead": {
        "start": 19,
        "end": 24,
        "fps": 6,
        "repeat": 0,
        "h": 214
      }
    }
  },
  "angely_boomerang": {
    "file": "assets/runtime/angely_boomerang.webp",
    "frameWidth": 220,
    "frameHeight": 224,
    "originX": 0.5699,
    "originY": 0.9821,
    "bodyHeight": 216,
    "anims": {
      "throw": {
        "start": 0,
        "end": 4,
        "fps": 18,
        "repeat": 0,
        "h": 212
      }
    }
  },
  "angely_wand": {
    "file": "assets/runtime/angely_wand.webp",
    "frameWidth": 249,
    "frameHeight": 293,
    "originX": 0.3564,
    "originY": 0.9863,
    "bodyHeight": 285,
    "anims": {
      "cast": {
        "start": 0,
        "end": 4,
        "fps": 16,
        "repeat": 0,
        "h": 218
      }
    }
  },
  "angely_ray": {
    "file": "assets/runtime/angely_ray.webp",
    "frameWidth": 243,
    "frameHeight": 251,
    "originX": 0.475,
    "originY": 0.9841,
    "bodyHeight": 243,
    "anims": {
      "shoot": {
        "start": 0,
        "end": 5,
        "fps": 16,
        "repeat": 0,
        "h": 235
      }
    }
  },
  "stormbird": {
    "file": "assets/runtime/stormbird.webp",
    "frameWidth": 145,
    "frameHeight": 182,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 130,
    "anims": {
      "idle": {
        "start": 0,
        "end": 9,
        "fps": 10,
        "repeat": -1,
        "h": 129
      },
      "walk": {
        "start": 10,
        "end": 19,
        "fps": 14,
        "repeat": -1,
        "h": 129
      },
      "attack": {
        "start": 20,
        "end": 29,
        "fps": 16,
        "repeat": 0,
        "h": 133
      },
      "hurt": {
        "start": 30,
        "end": 33,
        "fps": 12,
        "repeat": 0,
        "h": 124
      },
      "dead": {
        "start": 34,
        "end": 39,
        "fps": 10,
        "repeat": 0,
        "h": 145
      }
    }
  },
  "thunderimp": {
    "file": "assets/runtime/stormcloud2.webp",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 105,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 201 },
      "walk": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 201 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 201 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 201 },
      "dead": { "start": 18, "end": 19, "fps": 6, "repeat": 0, "h": 201 }
    }
  },
  "jellyfish": {
    "file": "assets/runtime/jellyfish.webp",
    "frameWidth": 143,
    "frameHeight": 187,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 151,
    "anims": {
      "idle": {
        "start": 0,
        "end": 9,
        "fps": 10,
        "repeat": -1,
        "h": 150
      },
      "walk": {
        "start": 10,
        "end": 19,
        "fps": 14,
        "repeat": -1,
        "h": 150
      },
      "attack": {
        "start": 20,
        "end": 29,
        "fps": 16,
        "repeat": 0,
        "h": 152
      },
      "hurt": {
        "start": 30,
        "end": 33,
        "fps": 12,
        "repeat": 0,
        "h": 161
      },
      "dead": {
        "start": 34,
        "end": 39,
        "fps": 10,
        "repeat": 0,
        "h": 165
      }
    }
  },
  "anglerfish": {
    "file": "assets/runtime/anglerfish.webp",
    "frameWidth": 126,
    "frameHeight": 155,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 110,
    "anims": {
      "idle": {
        "start": 0,
        "end": 9,
        "fps": 10,
        "repeat": -1,
        "h": 107
      },
      "walk": {
        "start": 10,
        "end": 19,
        "fps": 14,
        "repeat": -1,
        "h": 107
      },
      "attack": {
        "start": 20,
        "end": 29,
        "fps": 16,
        "repeat": 0,
        "h": 110
      },
      "hurt": {
        "start": 30,
        "end": 33,
        "fps": 12,
        "repeat": 0,
        "h": 133
      },
      "dead": {
        "start": 34,
        "end": 39,
        "fps": 10,
        "repeat": 0,
        "h": 123
      }
    }
  },
  "angely_swim": {
    "file": "assets/runtime/angely_swim.webp",
    "frameWidth": 190,
    "frameHeight": 287,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 196,
    "anims": {
      "swim": {
        "start": 0,
        "end": 7,
        "fps": 12,
        "repeat": -1,
        "h": 180
      },
      "float": {
        "start": 8,
        "end": 13,
        "fps": 7,
        "repeat": -1,
        "h": 236
      },
      "up": {
        "start": 14,
        "end": 17,
        "fps": 14,
        "repeat": 0,
        "h": 245
      },
      "hurt": {
        "start": 18,
        "end": 19,
        "fps": 10,
        "repeat": 0,
        "h": 238
      }
    }
  },
  "angelo": {
    "file": "assets/runtime/angelo.webp",
    "frameWidth": 321,
    "frameHeight": 251,
    "originX": 0.313,
    "originY": 0.9841,
    "bodyHeight": 232,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 231
      },
      "run": {
        "start": 4,
        "end": 11,
        "fps": 14,
        "repeat": -1,
        "h": 211
      },
      "talk": {
        "start": 12,
        "end": 15,
        "fps": 7,
        "repeat": -1,
        "h": 233
      },
      "wave": {
        "start": 16,
        "end": 19,
        "fps": 7,
        "repeat": -1,
        "h": 237
      },
      "arms": {
        "start": 20,
        "end": 21,
        "fps": 2,
        "repeat": -1,
        "h": 238
      },
      "welcome": {
        "start": 22,
        "end": 23,
        "fps": 5,
        "repeat": 0,
        "h": 238
      },
      "stance": {
        "start": 24,
        "end": 24,
        "fps": 1,
        "repeat": -1,
        "h": 208
      },
      "crouch": {
        "start": 25,
        "end": 25,
        "fps": 1,
        "repeat": -1,
        "h": 189
      },
      "leap": {
        "start": 26,
        "end": 26,
        "fps": 1,
        "repeat": -1,
        "h": 229
      },
      "kick": {
        "start": 27,
        "end": 28,
        "fps": 12,
        "repeat": 0,
        "h": 202
      },
      "drop": {
        "start": 29,
        "end": 29,
        "fps": 1,
        "repeat": -1,
        "h": 152
      },
      "punch": {
        "start": 30,
        "end": 32,
        "fps": 12,
        "repeat": 0,
        "h": 209
      },
      "uppercut": {
        "start": 33,
        "end": 34,
        "fps": 10,
        "repeat": 0,
        "h": 205
      },
      "land": {
        "start": 35,
        "end": 35,
        "fps": 1,
        "repeat": -1,
        "h": 173
      }
    }
  },
  "angelo_hug": {
    "file": "assets/runtime/angelo_hug.webp",
    "frameWidth": 219,
    "frameHeight": 252,
    "originX": 0.5,
    "originY": 0.9841,
    "bodyHeight": 238,
    "anims": {
      "open": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 238
      },
      "kneel": {
        "start": 1,
        "end": 1,
        "fps": 1,
        "repeat": -1,
        "h": 212
      },
      "hug": {
        "start": 2,
        "end": 5,
        "fps": 3,
        "repeat": -1,
        "h": 230
      },
      "pat": {
        "start": 6,
        "end": 6,
        "fps": 1,
        "repeat": -1,
        "h": 244
      }
    }
  },
  "colossus": {
    "file": "assets/runtime/colossus.webp",
    "frameWidth": 328,
    "frameHeight": 285,
    "originX": 0.5854,
    "originY": 0.986,
    "bodyHeight": 270,
    "anims": {
      "idle": {
        "start": 0,
        "end": 1,
        "fps": 2,
        "repeat": -1,
        "h": 268
      },
      "roar": {
        "start": 2,
        "end": 2,
        "fps": 1,
        "repeat": -1,
        "h": 277
      },
      "smash": {
        "start": 3,
        "end": 3,
        "fps": 1,
        "repeat": -1,
        "h": 249
      },
      "hurt": {
        "start": 4,
        "end": 5,
        "fps": 6,
        "repeat": 0,
        "h": 260
      },
      "fall": {
        "start": 6,
        "end": 8,
        "fps": 4,
        "repeat": 0,
        "h": 192
      }
    }
  },
  "weapon_cog": {
    "file": "assets/runtime/weapon_cog.webp",
    "frameWidth": 399,
    "frameHeight": 400,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 392,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 392
      }
    }
  },
  "weapon_boomerang": {
    "file": "assets/runtime/weapon_boomerang.webp",
    "frameWidth": 124,
    "frameHeight": 182,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 174,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 174
      }
    }
  },
  "weapon_wand": {
    "file": "assets/runtime/weapon_wand.webp",
    "frameWidth": 106,
    "frameHeight": 218,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 210,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 210
      }
    }
  },
  "fx_star": {
    "file": "assets/runtime/fx_star.webp",
    "frameWidth": 160,
    "frameHeight": 44,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 36,
    "anims": {
      "fly": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 36
      }
    }
  },
  "weapon_bow": {
    "file": "assets/runtime/weapon_bow.webp",
    "frameWidth": 115,
    "frameHeight": 240,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 232,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 232
      }
    }
  },
  "weapon_hammer": {
    "file": "assets/runtime/weapon_hammer.webp",
    "frameWidth": 134,
    "frameHeight": 202,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 194,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 194
      }
    }
  },
  "fx_arrow": {
    "file": "assets/runtime/fx_arrow.webp",
    "frameWidth": 139,
    "frameHeight": 35,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 27,
    "anims": {
      "fly": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 27
      }
    }
  },
  "angely_sword": {
    "file": "assets/runtime/angely_sword.webp",
    "frameWidth": 397,
    "frameHeight": 325,
    "originX": 0.4558,
    "originY": 0.9877,
    "bodyHeight": 208,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 6,
        "repeat": -1,
        "h": 206
      },
      "slash": {
        "start": 4,
        "end": 8,
        "fps": 18,
        "repeat": 0,
        "h": 198
      },
      "jump_attack": {
        "start": 9,
        "end": 12,
        "fps": 14,
        "repeat": 0,
        "h": 212
      },
      "pickup": {
        "start": 13,
        "end": 15,
        "fps": 4,
        "repeat": 0,
        "h": 262
      },
      "hurt": {
        "start": 16,
        "end": 17,
        "fps": 8,
        "repeat": 0,
        "h": 219
      },
      "defeat": {
        "start": 18,
        "end": 20,
        "fps": 5,
        "repeat": 0,
        "h": 180
      }
    }
  },
  "mushroom": {
    "file": "assets/runtime/mushroom.webp",
    "frameWidth": 171,
    "frameHeight": 182,
    "originX": 0.4766,
    "originY": 0.978,
    "bodyHeight": 174,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 171
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 171
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 168
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 116
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 90
      }
    }
  },
  "beetle": {
    "file": "assets/runtime/goldenscarab.webp",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.493,
    "originY": 0.9755,
    "bodyHeight": 155,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 163 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 163 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 163 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 163 },
      "dead": { "start": 18, "end": 19, "fps": 6, "repeat": 0, "h": 163 }
    }
  },
  "leafimp": {
    "file": "assets/runtime/leafimp.webp",
    "frameWidth": 260,
    "frameHeight": 208,
    "originX": 0.4397,
    "originY": 0.9808,
    "bodyHeight": 200,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 196
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 196
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 185
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 181
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 145
      }
    }
  },
  "firefly": {
    "file": "assets/runtime/firefly.webp",
    "frameWidth": 151,
    "frameHeight": 154,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 146,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 141
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 141
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 125
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 127
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 95
      }
    }
  },
  "golem": {
    "file": "assets/runtime/golem.webp",
    "frameWidth": 257,
    "frameHeight": 294,
    "originX": 0.4995,
    "originY": 0.9864,
    "bodyHeight": 245,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 241
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 241
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 283
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 218
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 175
      }
    }
  },
  "gargoyle": {
    "file": "assets/runtime/gargoyle.webp",
    "frameWidth": 706,
    "frameHeight": 236,
    "originX": 0.5,
    "originY": 0.98,
    "bodyHeight": 220,
    "anims": {
      "idle": { "start": 0, "end": 5, "fps": 6, "repeat": -1, "h": 220 },
      "walk": { "start": 6, "end": 12, "fps": 8, "repeat": -1, "h": 220 },
      "wakeup": { "start": 13, "end": 18, "fps": 8, "repeat": 0, "h": 220 },
      "attack": { "start": 19, "end": 22, "fps": 8, "repeat": 0, "h": 220 },
      "hurt": { "start": 26, "end": 30, "fps": 8, "repeat": 0, "h": 220 },
      "dead": { "start": 31, "end": 36, "fps": 6, "repeat": 0, "h": 220 }
    }
  },
  "pufferfish": {
    "file": "assets/runtime/pufferfish.webp",
    "frameWidth": 893,
    "frameHeight": 236,
    "originX": 0.5,
    "originY": 0.98,
    "bodyHeight": 220,
    "anims": {
      "idle": { "start": 0, "end": 5, "fps": 6, "repeat": -1, "h": 220 },
      "walk": { "start": 6, "end": 11, "fps": 8, "repeat": -1, "h": 220 },
      "attack": { "start": 18, "end": 21, "fps": 8, "repeat": 0, "h": 220 },
      "hurt": { "start": 24, "end": 29, "fps": 8, "repeat": 0, "h": 220 },
      "dead": { "start": 30, "end": 35, "fps": 6, "repeat": 0, "h": 220 }
    }
  },
  "lavalizard": {
    "file": "assets/runtime/lavalizard.webp",
    "frameWidth": 580,
    "frameHeight": 236,
    "originX": 0.5,
    "originY": 0.98,
    "bodyHeight": 220,
    "anims": {
      "idle": { "start": 0, "end": 2, "fps": 6, "repeat": -1, "h": 220 },
      "walk": { "start": 3, "end": 8, "fps": 8, "repeat": -1, "h": 220 },
      "attack": { "start": 9, "end": 12, "fps": 8, "repeat": 0, "h": 220 },
      "hurt": { "start": 15, "end": 17, "fps": 8, "repeat": 0, "h": 220 },
      "dead": { "start": 18, "end": 21, "fps": 6, "repeat": 0, "h": 220 }
    }
  },
  "acorn": {
    "file": "assets/runtime/acorn.webp",
    "frameWidth": 493,
    "frameHeight": 236,
    "originX": 0.5,
    "originY": 0.98,
    "bodyHeight": 220,
    "anims": {
      "idle": { "start": 0, "end": 3, "fps": 6, "repeat": -1, "h": 220 },
      "walk": { "start": 4, "end": 9, "fps": 8, "repeat": -1, "h": 220 },
      "attack": { "start": 16, "end": 21, "fps": 8, "repeat": 0, "h": 220 },
      "hurt": { "start": 22, "end": 25, "fps": 8, "repeat": 0, "h": 220 },
      "dead": { "start": 26, "end": 30, "fps": 6, "repeat": 0, "h": 220 }
    }
  },
  "storm_eagle": {
    "file": "assets/props/storm_eagle.webp",
    "frameWidth": 200, "frameHeight": 143, "originX": 0.5, "originY": 0.98, "bodyHeight": 135,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 135 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 135 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 135 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 135 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 135 }
    }
  },
  "storm_cloud": {
    "file": "assets/props/storm_cloud.webp",
    "frameWidth": 159, "frameHeight": 200, "originX": 0.5, "originY": 0.98, "bodyHeight": 190,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 190 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 190 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 190 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 190 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 190 }
    }
  },
  "lava_turtle": {
    "file": "assets/props/lava_turtle.webp",
    "frameWidth": 200, "frameHeight": 144, "originX": 0.5, "originY": 0.98, "bodyHeight": 136,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 136 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 136 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 136 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 136 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 136 }
    }
  },
  "lava_wisp": {
    "file": "assets/props/lava_wisp.webp",
    "frameWidth": 188, "frameHeight": 200, "originX": 0.5, "originY": 0.98, "bodyHeight": 190,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 190 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 190 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 190 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 190 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 190 }
    }
  },
  "ocean_jelly": {
    "file": "assets/props/ocean_jelly.webp",
    "frameWidth": 200, "frameHeight": 177, "originX": 0.5, "originY": 0.98, "bodyHeight": 168,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 168 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 168 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 168 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 168 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 168 }
    }
  },
  "ocean_crab": {
    "file": "assets/props/ocean_crab.webp",
    "frameWidth": 200, "frameHeight": 132, "originX": 0.5, "originY": 0.98, "bodyHeight": 124,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 124 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 124 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 124 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 124 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 124 }
    }
  },
  "desert_scarab": {
    "file": "assets/props/desert_scarab.webp",
    "frameWidth": 200, "frameHeight": 132, "originX": 0.5, "originY": 0.98, "bodyHeight": 124,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 124 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 124 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 124 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 124 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 124 }
    }
  },
  "desert_spirit": {
    "file": "assets/props/desert_spirit.webp",
    "frameWidth": 200, "frameHeight": 196, "originX": 0.5, "originY": 0.98, "bodyHeight": 186,
    "anims": {
      "idle": { "start": 0, "end": 0, "fps": 6, "repeat": -1, "h": 186 },
      "walk": { "start": 0, "end": 0, "fps": 8, "repeat": -1, "h": 186 },
      "attack": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 186 },
      "hurt": { "start": 0, "end": 0, "fps": 8, "repeat": 0, "h": 186 },
      "dead": { "start": 0, "end": 0, "fps": 6, "repeat": 0, "h": 186 }
    }
  },
  "ghost": {
    "file": "assets/runtime/purpleghost2.webp",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 195,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 218 },
      "walk": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 218 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 218 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 218 },
      "dead": { "start": 18, "end": 19, "fps": 6, "repeat": 0, "h": 218 }
    }
  },
  "forest_slime": {
    "file": "assets/runtime/forest_slime.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 150,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 150 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 150 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 150 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 150 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 150 }
    }
  },
  "crystal_spider": {
    "file": "assets/runtime/crystal_spider.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "gem_golem": {
    "file": "assets/runtime/gem_golem.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 180,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 180 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 180 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 180 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 180 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 180 }
    }
  },
  "swamp_crawler": {
    "file": "assets/runtime/swamp_crawler.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 150,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 150 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 150 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 150 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 150 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 150 }
    }
  },
  "bog_witch": {
    "file": "assets/runtime/bog_witch.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "jungle_tiger": {
    "file": "assets/runtime/jungle_tiger.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "vine_serpent": {
    "file": "assets/runtime/vine_serpent.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "storm_roc": {
    "file": "assets/runtime/storm_roc.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "tempest_eagle": {
    "file": "assets/runtime/tempest_eagle.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "thunder_golem": {
    "file": "assets/runtime/thunder_golem.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "ghost_knight": {
    "file": "assets/runtime/ghost_knight.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "zombie_hound": {
    "file": "assets/runtime/zombie_hound.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "candy_golem": {
    "file": "assets/runtime/candy_golem.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "licorice_witch": {
    "file": "assets/runtime/licorice_witch.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "abyss_shark": {
    "file": "assets/runtime/abyss_shark.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "jellyfish_queen": {
    "file": "assets/runtime/jellyfish_queen.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "clockwork_soldier": {
    "file": "assets/runtime/clockwork_soldier.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "gear_spider": {
    "file": "assets/runtime/gear_spider.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "void_walker": {
    "file": "assets/runtime/void_walker.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "star_eater": {
    "file": "assets/runtime/star_eater.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "baby_dragon": {
    "file": "assets/runtime/baby_dragon.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "fire_imp": {
    "file": "assets/runtime/fire_imp.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "umbra_guard": {
    "file": "assets/runtime/umbra_guard.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "shadow_lord": {
    "file": "assets/runtime/shadow_lord.png",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 160,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 160 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 160 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 160 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 160 },
      "dead": { "start": 17, "end": 19, "fps": 6, "repeat": 0, "h": 160 }
    }
  },
  "lantern": {
    "file": "assets/runtime/lantern.webp",
    "frameWidth": 188,
    "frameHeight": 204,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 196,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 195
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 195
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 192
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 179
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 159
      }
    }
  },
  "skeleton": {
    "file": "assets/runtime/skeleton.webp",
    "frameWidth": 239,
    "frameHeight": 247,
    "originX": 0.5091,
    "originY": 0.9838,
    "bodyHeight": 224,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 221
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 221
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 222
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 208
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 182
      }
    }
  },
  "firebat": {
    "file": "assets/runtime/firebat3.webp",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 156,
    "anims": {
      "idle": { "start": 0, "end": 3, "fps": 8, "repeat": -1, "h": 119 },
      "walk": { "start": 0, "end": 3, "fps": 8, "repeat": -1, "h": 119 },
      "attack": { "start": 8, "end": 11, "fps": 10, "repeat": 0, "h": 119 },
      "hurt": { "start": 12, "end": 13, "fps": 8, "repeat": 0, "h": 119 },
      "dead": { "start": 16, "end": 19, "fps": 6, "repeat": 0, "h": 119 }
    }
  },
  "lavablob": {
    "file": "assets/runtime/lavablob.webp",
    "frameWidth": 205,
    "frameHeight": 162,
    "originX": 0.3877,
    "originY": 0.9753,
    "bodyHeight": 154,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 131
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 131
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 145
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 73
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 61
      }
    }
  },
  "crab": {
    "file": "assets/runtime/crab.webp",
    "frameWidth": 229,
    "frameHeight": 180,
    "originX": 0.4235,
    "originY": 0.9778,
    "bodyHeight": 165,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 163
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 163
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 160
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 148
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 136
      }
    }
  },
  "magmagolem": {
    "file": "assets/runtime/magmagolem.webp",
    "frameWidth": 282,
    "frameHeight": 313,
    "originX": 0.5176,
    "originY": 0.9872,
    "bodyHeight": 262,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 260
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 260
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 296
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 260
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 183
      }
    }
  },
  "cogmoth": {
    "file": "assets/runtime/cogmoth.webp",
    "frameWidth": 232,
    "frameHeight": 176,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 168,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 157
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 157
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 103
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 144
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 112
      }
    }
  },
  "gearcrab": {
    "file": "assets/runtime/gearcrab.webp",
    "frameWidth": 275,
    "frameHeight": 178,
    "originX": 0.4276,
    "originY": 0.9775,
    "bodyHeight": 170,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 170
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 170
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 167
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 170
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 135
      }
    }
  },
  "sandwisp": {
    "file": "assets/runtime/sandwisp.webp",
    "frameWidth": 279,
    "frameHeight": 190,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 166,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 161
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 161
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 173
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 167
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 127
      }
    }
  },
  "frostwolf": {
    "file": "assets/runtime/icewolf3.webp",
    "frameWidth": 220,
    "frameHeight": 220,
    "originX": 0.4206,
    "originY": 0.9778,
    "bodyHeight": 172,
    "anims": {
      "idle": { "start": 0, "end": 4, "fps": 8, "repeat": -1, "h": 171 },
      "walk": { "start": 5, "end": 9, "fps": 8, "repeat": -1, "h": 171 },
      "attack": { "start": 10, "end": 14, "fps": 10, "repeat": 0, "h": 171 },
      "hurt": { "start": 15, "end": 16, "fps": 8, "repeat": 0, "h": 171 },
      "dead": { "start": 18, "end": 19, "fps": 6, "repeat": 0, "h": 171 }
    }
  },
  "icewisp": {
    "file": "assets/runtime/icewisp.webp",
    "frameWidth": 160,
    "frameHeight": 170,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 153,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 151
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 151
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 139
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 142
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 148
      }
    }
  },
  "penguin": {
    "file": "assets/runtime/penguin.webp",
    "frameWidth": 190,
    "frameHeight": 170,
    "originX": 0.5379,
    "originY": 0.9765,
    "bodyHeight": 162,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 161
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 161
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 154
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 151
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 119
      }
    }
  },
  "yeti": {
    "file": "assets/runtime/yeti.webp",
    "frameWidth": 302,
    "frameHeight": 267,
    "originX": 0.4638,
    "originY": 0.985,
    "bodyHeight": 257,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 254
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 254
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 252
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 218
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 192
      }
    }
  },
  "fx_fireball": {
    "file": "assets/runtime/fx_fireball.webp",
    "frameWidth": 175,
    "frameHeight": 106,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 59,
    "anims": {
      "fly": {
        "start": 0,
        "end": 3,
        "fps": 12,
        "repeat": -1,
        "h": 50
      },
      "impact": {
        "start": 4,
        "end": 5,
        "fps": 14,
        "repeat": 0,
        "h": 87
      }
    }
  },
  "fx_orb": {
    "file": "assets/runtime/fx_orb.webp",
    "frameWidth": 160,
    "frameHeight": 106,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 76,
    "anims": {
      "fly": {
        "start": 0,
        "end": 3,
        "fps": 12,
        "repeat": -1,
        "h": 69
      },
      "impact": {
        "start": 4,
        "end": 5,
        "fps": 14,
        "repeat": 0,
        "h": 87
      }
    }
  },
  "fx_bolt": {
    "file": "assets/runtime/fx_bolt.webp",
    "frameWidth": 177,
    "frameHeight": 106,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 62,
    "anims": {
      "fly": {
        "start": 0,
        "end": 3,
        "fps": 12,
        "repeat": -1,
        "h": 53
      },
      "impact": {
        "start": 4,
        "end": 5,
        "fps": 14,
        "repeat": 0,
        "h": 87
      }
    }
  },
  "fx_spark": {
    "file": "assets/runtime/fx_spark.webp",
    "frameWidth": 138,
    "frameHeight": 92,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 84,
    "anims": {
      "hit": {
        "start": 0,
        "end": 3,
        "fps": 20,
        "repeat": 0,
        "h": 61
      }
    }
  },
  "fx_dust": {
    "file": "assets/runtime/fx_dust.webp",
    "frameWidth": 150,
    "frameHeight": 76,
    "originX": 0.4559,
    "originY": 0.9474,
    "bodyHeight": 68,
    "anims": {
      "puff": {
        "start": 0,
        "end": 3,
        "fps": 14,
        "repeat": 0,
        "h": 57
      }
    }
  },
  "fx_explode": {
    "file": "assets/runtime/fx_explode.webp",
    "frameWidth": 203,
    "frameHeight": 134,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 126,
    "anims": {
      "boom": {
        "start": 0,
        "end": 3,
        "fps": 14,
        "repeat": 0,
        "h": 92
      }
    }
  },
  "fx_slash": {
    "file": "assets/runtime/fx_slash.webp",
    "frameWidth": 149,
    "frameHeight": 155,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 147,
    "anims": {
      "swing": {
        "start": 0,
        "end": 4,
        "fps": 20,
        "repeat": 0,
        "h": 127
      }
    }
  },
  "fx_lava": {
    "file": "assets/runtime/fx_lava.webp",
    "frameWidth": 149,
    "frameHeight": 164,
    "originX": 0.502,
    "originY": 0.9756,
    "bodyHeight": 156,
    "anims": {
      "burst": {
        "start": 0,
        "end": 4,
        "fps": 10,
        "repeat": 0,
        "h": 134
      }
    }
  },
  "heart": {
    "file": "assets/runtime/heart.webp",
    "frameWidth": 117,
    "frameHeight": 97,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 89,
    "anims": {
      "glow": {
        "start": 0,
        "end": 2,
        "fps": 6,
        "repeat": -1,
        "h": 68
      }
    }
  },
  "flag": {
    "file": "assets/runtime/flag.webp",
    "frameWidth": 268,
    "frameHeight": 219,
    "originX": 0.4403,
    "originY": 0.9817,
    "bodyHeight": 206,
    "anims": {
      "down": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 206
      },
      "up": {
        "start": 1,
        "end": 1,
        "fps": 1,
        "repeat": -1,
        "h": 211
      }
    }
  },
  "spring": {
    "file": "assets/runtime/spring.webp",
    "frameWidth": 146,
    "frameHeight": 157,
    "originX": 0.5123,
    "originY": 0.9745,
    "bodyHeight": 149,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 149
      }
    }
  },
  "sword_stone": {
    "file": "assets/runtime/sword_stone.webp",
    "frameWidth": 194,
    "frameHeight": 219,
    "originX": 0.4907,
    "originY": 0.9817,
    "bodyHeight": 211,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 211
      }
    }
  },
  "portal": {
    "file": "assets/runtime/portal.webp",
    "frameWidth": 342,
    "frameHeight": 380,
    "originX": 0.3641,
    "originY": 0.9895,
    "bodyHeight": 372,
    "anims": {
      "arch": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 372
      }
    }
  },
  "vortex": {
    "file": "assets/runtime/vortex.webp",
    "frameWidth": 309,
    "frameHeight": 309,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 301,
    "anims": {
      "spin": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 301
      }
    }
  },
  "sandworm": {
    "file": "assets/runtime/sandworm.webp",
    "frameWidth": 341,
    "frameHeight": 295,
    "originX": 0.588,
    "originY": 0.9864,
    "bodyHeight": 287,
    "anims": {
      "rise": {
        "start": 0,
        "end": 3,
        "fps": 8,
        "repeat": 0,
        "h": 271
      },
      "idle": {
        "start": 4,
        "end": 4,
        "fps": 1,
        "repeat": -1,
        "h": 284
      },
      "spit": {
        "start": 5,
        "end": 6,
        "fps": 10,
        "repeat": 0,
        "h": 192
      },
      "hurt": {
        "start": 7,
        "end": 7,
        "fps": 8,
        "repeat": 0,
        "h": 221
      },
      "dive": {
        "start": 8,
        "end": 9,
        "fps": 8,
        "repeat": 0,
        "h": 208
      }
    }
  },
  "blob": {
    "file": "assets/runtime/blob.webp",
    "frameWidth": 242,
    "frameHeight": 234,
    "originX": 0.5,
    "originY": 0.9829,
    "bodyHeight": 194,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 172
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 172
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 185
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 173
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 159
      }
    }
  },
  "squish": {
    "file": "assets/runtime/squish.webp",
    "frameWidth": 229,
    "frameHeight": 246,
    "originX": 0.5,
    "originY": 0.9837,
    "bodyHeight": 212,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 5,
        "repeat": -1,
        "h": 192
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 192
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 7,
        "repeat": 0,
        "h": 229
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 184
      },
      "dead": {
        "start": 11,
        "end": 12,
        "fps": 6,
        "repeat": 0,
        "h": 151
      }
    }
  },
  "toxic": {
    "file": "assets/runtime/toxic.webp",
    "frameWidth": 240,
    "frameHeight": 219,
    "originX": 0.3708,
    "originY": 0.9817,
    "bodyHeight": 211,
    "anims": {
      "idle": {
        "start": 0,
        "end": 3,
        "fps": 6,
        "repeat": -1,
        "h": 188
      },
      "walk": {
        "start": 4,
        "end": 7,
        "fps": 8,
        "repeat": -1,
        "h": 188
      },
      "attack": {
        "start": 8,
        "end": 9,
        "fps": 10,
        "repeat": 0,
        "h": 185
      },
      "hurt": {
        "start": 10,
        "end": 10,
        "fps": 8,
        "repeat": 0,
        "h": 166
      },
      "dead": {
        "start": 11,
        "end": 11,
        "fps": 6,
        "repeat": 0,
        "h": 156
      }
    }
  },
  "weapon_ray": {
    "file": "assets/runtime/weapon_ray.webp",
    "frameWidth": 352,
    "frameHeight": 258,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 250,
    "anims": {
      "idle": {
        "start": 0,
        "end": 0,
        "fps": 1,
        "repeat": -1,
        "h": 250
      }
    }
  },
  "fx_ray": {
    "file": "assets/runtime/fx_ray.webp",
    "frameWidth": 255,
    "frameHeight": 119,
    "originX": 0.5,
    "originY": 0.5,
    "bodyHeight": 111,
    "anims": {
      "fly": {
        "start": 0,
        "end": 3,
        "fps": 16,
        "repeat": -1,
        "h": 111
      }
    }
  }
} as const;

export const PROPS = {
  "ground_1": {
    "file": "assets/runtime/props/ground_1.webp",
    "width": 640,
    "height": 57.6,
    "surface": 0.017
  },
  "plat_l_1": {
    "file": "assets/runtime/props/plat_l_1.webp",
    "width": 190,
    "height": 69.4,
    "surface": 0.058
  },
  "plat_m_1": {
    "file": "assets/runtime/props/plat_m_1.webp",
    "width": 145,
    "height": 61.1,
    "surface": 0.041
  },
  "plat_s_1": {
    "file": "assets/runtime/props/plat_s_1.webp",
    "width": 100,
    "height": 41.5,
    "surface": 0.048
  },
  "spikes_1": {
    "file": "assets/runtime/props/spikes_1.webp",
    "width": 100,
    "height": 59.4,
    "surface": 0.706
  },
  "crate_1": {
    "file": "assets/runtime/props/crate_1.webp",
    "width": 84,
    "height": 77.1,
    "surface": 0.006
  },
  "block_1": {
    "file": "assets/runtime/props/block_1.webp",
    "width": 84,
    "height": 74.9,
    "surface": 0.033
  },
  "ground_2": {
    "file": "assets/runtime/props/ground_2.webp",
    "width": 640,
    "height": 63.3,
    "surface": 0.039
  },
  "plat_l_2": {
    "file": "assets/runtime/props/plat_l_2.webp",
    "width": 190,
    "height": 89.0,
    "surface": 0.022
  },
  "plat_m_2": {
    "file": "assets/runtime/props/plat_m_2.webp",
    "width": 145,
    "height": 72.7,
    "surface": 0.028
  },
  "plat_s_2": {
    "file": "assets/runtime/props/plat_s_2.webp",
    "width": 100,
    "height": 64.6,
    "surface": 0.023
  },
  "spikes_2": {
    "file": "assets/runtime/props/spikes_2.webp",
    "width": 100,
    "height": 47.3,
    "surface": 0.726
  },
  "crate_2": {
    "file": "assets/runtime/props/crate_2.webp",
    "width": 84,
    "height": 71.2,
    "surface": 0.035
  },
  "block_2": {
    "file": "assets/runtime/props/block_2.webp",
    "width": 84,
    "height": 78.5,
    "surface": 0.025
  },
  "ground_3": {
    "file": "assets/runtime/props/ground_3.webp",
    "width": 640,
    "height": 60.1,
    "surface": 0.008
  },
  "plat_l_3": {
    "file": "assets/runtime/props/plat_l_3.webp",
    "width": 190,
    "height": 89.5,
    "surface": 0.006
  },
  "plat_m_3": {
    "file": "assets/runtime/props/plat_m_3.webp",
    "width": 145,
    "height": 74.6,
    "surface": 0.007
  },
  "plat_s_3": {
    "file": "assets/runtime/props/plat_s_3.webp",
    "width": 100,
    "height": 53.2,
    "surface": 0.009
  },
  "spikes_3": {
    "file": "assets/runtime/props/spikes_3.webp",
    "width": 100,
    "height": 45.2,
    "surface": 0.556
  },
  "crate_3": {
    "file": "assets/runtime/props/crate_3.webp",
    "width": 84,
    "height": 73.7,
    "surface": 0.027
  },
  "block_3": {
    "file": "assets/runtime/props/block_3.webp",
    "width": 84,
    "height": 59.8,
    "surface": 0.017
  },
  "ground_4": {
    "file": "assets/runtime/props/ground_4.webp",
    "width": 640,
    "height": 60.1,
    "surface": 0.15
  },
  "plat_l_4": {
    "file": "assets/runtime/props/plat_l_4.webp",
    "width": 190,
    "height": 95.2,
    "surface": 0.089
  },
  "plat_m_4": {
    "file": "assets/runtime/props/plat_m_4.webp",
    "width": 145,
    "height": 85.0,
    "surface": 0.088
  },
  "plat_s_4": {
    "file": "assets/runtime/props/plat_s_4.webp",
    "width": 100,
    "height": 58.9,
    "surface": 0.085
  },
  "spikes_4": {
    "file": "assets/runtime/props/spikes_4.webp",
    "width": 100,
    "height": 45.9,
    "surface": 0.543
  },
  "crate_4": {
    "file": "assets/runtime/props/crate_4.webp",
    "width": 84,
    "height": 72.5,
    "surface": 0.179
  },
  "block_4": {
    "file": "assets/runtime/props/block_4.webp",
    "width": 84,
    "height": 57.9,
    "surface": 0.155
  },
  "ground_5": {
    "file": "assets/runtime/props/ground_5.webp",
    "width": 640,
    "height": 62.4,
    "surface": 0.016
  },
  "plat_l_5": {
    "file": "assets/runtime/props/plat_l_5.webp",
    "width": 190,
    "height": 97.2,
    "surface": 0.0
  },
  "plat_m_5": {
    "file": "assets/runtime/props/plat_m_5.webp",
    "width": 145,
    "height": 87.8,
    "surface": 0.0
  },
  "plat_s_5": {
    "file": "assets/runtime/props/plat_s_5.webp",
    "width": 100,
    "height": 63.9,
    "surface": 0.0
  },
  "spikes_5": {
    "file": "assets/runtime/props/spikes_5.webp",
    "width": 100,
    "height": 47.7,
    "surface": 0.526
  },
  "crate_5": {
    "file": "assets/runtime/props/crate_5.webp",
    "width": 84,
    "height": 75.2,
    "surface": 0.027
  },
  "block_5": {
    "file": "assets/runtime/props/block_5.webp",
    "width": 84,
    "height": 62.8,
    "surface": 0.016
  },
  "ground_6": {
    "file": "assets/runtime/props/ground_6.webp",
    "width": 640,
    "height": 65.5,
    "surface": 0.374
  },
  "plat_l_6": {
    "file": "assets/runtime/props/plat_l_6.webp",
    "width": 190,
    "height": 80.1,
    "surface": 0.225
  },
  "plat_m_6": {
    "file": "assets/runtime/props/plat_m_6.webp",
    "width": 145,
    "height": 69.5,
    "surface": 0.237
  },
  "plat_s_6": {
    "file": "assets/runtime/props/plat_s_6.webp",
    "width": 100,
    "height": 50.6,
    "surface": 0.208
  },
  "spikes_6": {
    "file": "assets/runtime/props/spikes_6.webp",
    "width": 100,
    "height": 49.2,
    "surface": 0.52
  },
  "crate_6": {
    "file": "assets/runtime/props/crate_6.webp",
    "width": 84,
    "height": 75.6,
    "surface": 0.033
  },
  "block_6": {
    "file": "assets/runtime/props/block_6.webp",
    "width": 84,
    "height": 53.5,
    "surface": 0.224
  },
  "ground_7": {
    "file": "assets/runtime/props/ground_7.webp",
    "width": 640,
    "height": 69.6,
    "surface": 0.029
  },
  "plat_l_7": {
    "file": "assets/runtime/props/plat_l_7.webp",
    "width": 190,
    "height": 98.3,
    "surface": 0.005
  },
  "plat_m_7": {
    "file": "assets/runtime/props/plat_m_7.webp",
    "width": 145,
    "height": 94.2,
    "surface": 0.005
  },
  "plat_s_7": {
    "file": "assets/runtime/props/plat_s_7.webp",
    "width": 100,
    "height": 67.3,
    "surface": 0.007
  },
  "spikes_7": {
    "file": "assets/runtime/props/spikes_7.webp",
    "width": 100,
    "height": 48.4,
    "surface": 0.495
  },
  "crate_7": {
    "file": "assets/runtime/props/crate_7.webp",
    "width": 84,
    "height": 74.3,
    "surface": 0.034
  },
  "block_7": {
    "file": "assets/runtime/props/block_7.webp",
    "width": 84,
    "height": 64.8,
    "surface": 0.023
  },
  "ground_8": {
    "file": "assets/runtime/props/ground_8.webp",
    "width": 640,
    "height": 83.3,
    "surface": 0.078
  },
  "plat_l_8": {
    "file": "assets/runtime/props/plat_l_8.webp",
    "width": 190,
    "height": 57.8,
    "surface": 0.0
  },
  "plat_m_8": {
    "file": "assets/runtime/props/plat_m_8.webp",
    "width": 145,
    "height": 58.0,
    "surface": 0.009
  },
  "plat_s_8": {
    "file": "assets/runtime/props/plat_s_8.webp",
    "width": 100,
    "height": 50.9,
    "surface": 0.0
  },
  "spikes_8": {
    "file": "assets/runtime/props/spikes_8.webp",
    "width": 100,
    "height": 23.5,
    "surface": 0.404
  },
  "crate_8": {
    "file": "assets/runtime/props/crate_8.webp",
    "width": 84,
    "height": 70.5,
    "surface": 0.021
  },
  "block_8": {
    "file": "assets/runtime/props/block_8.webp",
    "width": 84,
    "height": 71.0,
    "surface": 0.0
  },
  "ground_9": {
    "file": "assets/runtime/props/ground_9.webp",
    "width": 640,
    "height": 74.6,
    "surface": 0.0
  },
  "plat_l_9": {
    "file": "assets/runtime/props/plat_l_9.webp",
    "width": 190,
    "height": 63.6,
    "surface": 0.0
  },
  "plat_m_9": {
    "file": "assets/runtime/props/plat_m_9.webp",
    "width": 145,
    "height": 65.0,
    "surface": 0.0
  },
  "plat_s_9": {
    "file": "assets/runtime/props/plat_s_9.webp",
    "width": 100,
    "height": 47.5,
    "surface": 0.0
  },
  "spikes_9": {
    "file": "assets/runtime/props/spikes_9.webp",
    "width": 100,
    "height": 34.6,
    "surface": 0.159
  },
  "ground_10": {
    "file": "assets/runtime/props/ground_10.webp",
    "width": 640,
    "height": 57.6,
    "surface": 0.017
  },
  "plat_l_10": {
    "file": "assets/runtime/props/plat_l_10.webp",
    "width": 190,
    "height": 69.4,
    "surface": 0.058
  },
  "plat_m_10": {
    "file": "assets/runtime/props/plat_m_10.webp",
    "width": 145,
    "height": 61.1,
    "surface": 0.058
  },
  "plat_s_10": {
    "file": "assets/runtime/props/plat_s_10.webp",
    "width": 100,
    "height": 41.5,
    "surface": 0.058
  },
  "spikes_10": {
    "file": "assets/runtime/props/spikes_10.webp",
    "width": 100,
    "height": 59.4,
    "surface": 0
  },
  "ground_11": {
    "file": "assets/runtime/props/ground_11.webp",
    "width": 640,
    "height": 57.6,
    "surface": 0.017
  },
  "plat_l_11": {
    "file": "assets/runtime/props/plat_l_11.webp",
    "width": 190,
    "height": 69.4,
    "surface": 0.058
  },
  "plat_m_11": {
    "file": "assets/runtime/props/plat_m_11.webp",
    "width": 145,
    "height": 61.1,
    "surface": 0.058
  },
  "plat_s_11": {
    "file": "assets/runtime/props/plat_s_11.webp",
    "width": 100,
    "height": 41.5,
    "surface": 0.058
  },
  "spikes_11": {
    "file": "assets/runtime/props/spikes_11.webp",
    "width": 100,
    "height": 59.4,
    "surface": 0
  },
  "crate_9": {
    "file": "assets/runtime/props/crate_9.webp",
    "width": 84,
    "height": 80.7,
    "surface": 0.025
  },
  "block_9": {
    "file": "assets/runtime/props/block_9.webp",
    "width": 84,
    "height": 74.2,
    "surface": 0.02
  }
} as const;

export const BACKDROPS = {
  "power_star": "assets/pickups/power-star.png",
  "bg1": "assets/runtime/backdrops/bg1.jpg",
  "bg2": "assets/runtime/backdrops/bg2.jpg",
  "bg3": "assets/runtime/backdrops/bg3.jpg",
  "bg4": "assets/runtime/backdrops/bg4.jpg",
  "bg5": "assets/runtime/backdrops/bg5.jpg",
  "bg6": "assets/runtime/backdrops/bg6.jpg",
  "bg7": "assets/runtime/backdrops/bg7.jpg",
  "bg8": "assets/runtime/backdrops/bg8.jpg",
  "title_bg": "assets/runtime/backdrops/title_bg.jpg",
  "title_splash": "assets/runtime/backdrops/title_splash.jpg",
  "splash1": "assets/runtime/backdrops/splash1.jpg",
  "splash2": "assets/runtime/backdrops/splash2.jpg",
  "splash3": "assets/runtime/backdrops/splash3.jpg",
  "splash4": "assets/runtime/backdrops/splash4.jpg",
  "splash5": "assets/runtime/backdrops/splash5.jpg",
  "splash6": "assets/runtime/backdrops/splash6.jpg",
  "splash7": "assets/runtime/backdrops/splash7.jpg",
  "splash8": "assets/runtime/backdrops/splash8.jpg",
  "portrait_angely": "assets/runtime/backdrops/portrait_angely.webp",
  "portrait_angely_wow": "assets/runtime/backdrops/portrait_angely_wow.webp",
  "portrait_angely_happy": "assets/runtime/backdrops/portrait_angely_happy.webp",
  "portrait_umbra": "assets/runtime/backdrops/portrait_umbra.webp",
  "portrait_angelo": "assets/runtime/backdrops/portrait_angelo.webp",
  "bg9": "assets/runtime/backdrops/bg9.jpg",
  "bg10": "assets/runtime/backdrops/bg10.jpg",
  "splash9": "assets/runtime/backdrops/splash9.jpg",
  "splash10": "assets/runtime/backdrops/splash10.jpg",
  "bg11": "assets/runtime/backdrops/bg11.jpg",
  "splash11": "assets/runtime/backdrops/splash11.jpg",
  "bg12": "assets/runtime/backdrops/bg12.jpg",
  "splash12": "assets/runtime/backdrops/splash12.jpg",
  "bg13": "assets/runtime/backdrops/bg13.jpg",
  "splash13": "assets/runtime/backdrops/splash13.jpg",
  "bg14": "assets/runtime/backdrops/bg14.jpg",
  "splash14": "assets/runtime/backdrops/splash14.jpg",
  "bg15": "assets/runtime/backdrops/bg15.jpg",
  "splash15": "assets/runtime/backdrops/splash15.jpg",
  "bg16": "assets/runtime/backdrops/bg16.jpg",
  "splash16": "assets/runtime/backdrops/splash16.jpg",
  "bg17": "assets/runtime/backdrops/bg17.jpg",
  "splash17": "assets/runtime/backdrops/splash17.jpg",
  "bg18": "assets/runtime/backdrops/bg18.jpg",
  "splash18": "assets/runtime/backdrops/splash18.jpg",
  "bg19": "assets/runtime/backdrops/bg19.jpg",
  "splash19": "assets/runtime/backdrops/splash19.jpg",
  "bg20": "assets/runtime/backdrops/bg20.jpg",
  "splash20": "assets/runtime/backdrops/splash20.jpg"
} as const;

export type SpriteKey = keyof typeof SPRITES;
export type PropKey = keyof typeof PROPS;
