const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const out=path.resolve('../finale-evidence');fs.mkdirSync(out,{recursive:true});
const result={checks:[],errors:[],screenshots:[],fixtures:'Shield refresh, positioning, phase damage and accelerated wave scheduling; actual keyboard ray and stomp verified. Not an unaided playthrough.'};
let browser,page;
(async()=>{
 const native=Boolean(process.env.CH11_CDP_URL),prefix=native?'android':'web';
 browser=native?await chromium.connectOverCDP(process.env.CH11_CDP_URL,{noDefaults:true}):await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']});
 page=native?browser.contexts()[0].pages()[0]:await browser.newPage({viewport:{width:1440,height:810},hasTouch:true});
 page.on('pageerror',e=>result.errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'||m.text().includes('[assets] failed'))result.errors.push(m.text())});
 const cdp=await page.context().newCDPSession(page);
 const base=native?'https://localhost/':'http://127.0.0.1:41811/';
 const wait=async(fn,timeout=25000)=>page.waitForFunction(fn,{},{timeout});
 const shot=async(name)=>{
  const file=path.join(out,prefix+'-'+name+'.png');
  if(native){const adb=path.join(process.env.ANDROID_HOME,'platform-tools','adb.exe'),remote='/sdcard/angelys-finale-qa.png';
   execFileSync(adb,['-s','emulator-5554','shell','screencap','-p',remote],{stdio:'pipe'});
   execFileSync(adb,['-s','emulator-5554','pull',remote,file],{stdio:'pipe'});
  }else await page.screenshot({path:file});
  result.screenshots.push(file);
 };
 const ev=fn=>page.evaluate(fn);
 const skip=async()=>{await wait(()=>window.__game.scene.getScene('Hud').dialogue.active);await page.keyboard.press('Escape')};
 const fight=async(fast=false)=>{
  await page.goto(base+'?level=11-2&res=1.5',{waitUntil:'networkidle'});
  await wait(()=>window.__game?.scene.getScene('Game')?.player,60000);
  if(fast)await ev(()=>{const s=window.__game.scene.getScene('Game');s.player.body.reset(s.level.arena.x0+180,450)});
  else await page.keyboard.down('ArrowRight');
  await wait(()=>window.__game.scene.getScene('Game').veilState==='intro',30000);
  await page.keyboard.up('ArrowRight');await skip();
  await wait(()=>window.__game.scene.getScene('Game').veilState==='fight');
  await ev(()=>{clearInterval(window.__qaShield);window.__qaShield=setInterval(()=>window.__game.scene.getScene('Game')?.player?.grantShield(),1000);window.__game.scene.getScene('Game').player.grantShield()});
 };
 const damage=async(amount)=>{await page.waitForTimeout(300);return page.evaluate(amount=>{const s=window.__game.scene.getScene('Game');return s.boss.takeDamage(amount,'sword',s.player.x)},amount)};
 await fight();
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').boss.hp),160);
 await shot('final-battle');
 await ev(()=>{const s=window.__game.scene.getScene('Game');s.player.body.reset(s.boss.x-300,450);s.player.facing=1;s.player.giveWeapon('ray');s.publishWeapons()});
 await page.keyboard.press('j',{delay:80});
 await wait(()=>window.__game.scene.getScene('Game').boss.hp<160,7000);
 result.checks.push(prefix+':160 HP; actual ray input damages final boss');
 await page.waitForTimeout(400);
 await ev(()=>{const s=window.__game.scene.getScene('Game'),b=s.boss,p=s.player,h=b.hitbox();
  const original=b.takeDamage.bind(b);window.__qaStomp=null;
  b.takeDamage=(amount,kind,x)=>{const before=b.hp,accepted=original(amount,kind,x);
   if(kind==='stomp'&&accepted){window.__qaStomp={delta:before-b.hp,vy:p.body.velocity.y};b.takeDamage=original;p.body.reset(b.x-300,450);}
   return accepted;
  };
  p.state='normal';p.body.reset(b.x,h.top-p.body.height/2-44);p.body.setVelocity(0,300);
 });
 await wait(()=>window.__qaStomp,5000);
 const stomp=await ev(()=>window.__qaStomp);
 assert.equal(stomp.delta,.25);assert(stomp.vy<0);
 result.checks.push(prefix+': actual descending collision bounces and removes exactly0.25 HP');
 await page.waitForTimeout(300);
 await ev(()=>{const s=window.__game.scene.getScene('Game');s.player.body.reset(s.boss.x-300,450)});
 await wait(()=>{const s=window.__game.scene.getScene('Game');return s.boss.attacking&&s.boss.strikeFrom-s.time.now>250},15000);
 const attack=await ev(()=>{const s=window.__game.scene.getScene('Game'),b=s.boss;const before=b.state,action=b.action,hp=b.hp;const accepted=b.takeDamage(2,'stomp',s.player.x);return {before,after:b.state,action,afterAction:b.action,delta:hp-b.hp,accepted}});
 assert(attack.accepted);assert.equal(attack.delta,.25);assert.equal(attack.before,attack.after);assert.equal(attack.action,attack.afterAction);
 result.checks.push(prefix+': stomp cannot cancel a warned boss attack');
 await wait(()=>window.__game.scene.getScene('Game').enemies.length>=2,12000);
 const first=await ev(()=>window.__game.scene.getScene('Game').enemies.map(e=>e.type.key));
 assert(first.includes('skeleton')&&first.includes('firebat'));
 await shot('mixed-wave');
 await page.waitForTimeout(300);
 assert(await ev(()=>{const s=window.__game.scene.getScene('Game');window.__oldVeilEffects=[...s.boss.effects];return s.boss.takeDamage(s.boss.hp-90,'sword',s.player.x)}));
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').boss.phase),2);
 assert.equal(await ev(()=>window.__oldVeilEffects.every(x=>!x.active)),true);
 await ev(()=>{const s=window.__game.scene.getScene('Game');s.enemies.forEach(e=>e.remove());s.enemies=[];s.nextVeilWave=0});
 await page.waitForTimeout(1400);
 const second=await ev(()=>window.__game.scene.getScene('Game').enemies.map(e=>e.type.key));
 assert(second.includes('lavablob'));assert(second.length<=3);
 await wait(()=>{const s=window.__game.scene.getScene('Game');return s.boss.state==='erupt'&&s.time.now<s.boss.strikeFrom},20000);
 await shot('phase2-warning');
 await wait(()=>window.__game.scene.getScene('Game').hazards.getLength()>0,5000);
 await shot('phase2-spikes');
 await wait(()=>window.__game.scene.getScene('Game').boss.state==='recover',5000);
 assert(await damage(50));assert.equal(await ev(()=>window.__game.scene.getScene('Game').boss.phase),3);
 await ev(()=>{const s=window.__game.scene.getScene('Game');s.enemies.forEach(e=>e.remove());s.enemies=[];s.nextVeilWave=0});
 await wait(()=>{const s=window.__game.scene.getScene('Game');return s.boss.state==='beam'&&s.time.now<s.boss.strikeFrom},7000);
 await shot('phase3-warning');await page.keyboard.press('Space',{delay:300});
 await wait(()=>window.__game.scene.getScene('Game').hazards.getLength()>0,5000);
 await shot('phase3-beam');
 await wait(()=>window.__game.scene.getScene('Game').boss.state==='recover',5000);
 result.checks.push(prefix+': faster three-phase attacks, visible crystal/beam warnings; mixed existing enemy waves stay capped');
 await page.waitForTimeout(300);
 assert(await ev(()=>{const s=window.__game.scene.getScene('Game');s.enemies.forEach(e=>e.remove());s.enemies=[];s.nextVeilWave=Infinity;s.player.body.reset(s.boss.x-300,450);s.player.facing=1;return s.boss.takeDamage(s.boss.hp-3,'sword',s.player.x)}));
 for(let i=0;i<10;i++){if(await ev(()=>window.__game.scene.getScene('Game').boss.hp===0))break;await page.waitForTimeout(400);await page.keyboard.press('j',{delay:80});}
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').boss.hp),0);
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').boss.timers.size),0);
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').enemies.length),0);
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').veilSummons.size),0);
 await skip();await skip();
 await wait(()=>window.__game.scene.getScene('Game').children.list.some(x=>x.texture?.key==='final_pair_reunion'&&x.active));
 await page.waitForTimeout(1000);await shot('reunion-hug');
 await wait(()=>window.__game.scene.getScene('Game').veilState==='together'&&window.__game.scene.getScene('Hud').dialogue.active,15000);
 await shot('take-my-hand');await skip();
 await wait(()=>window.__game.scene.getScene('Game').children.list.some(x=>x.texture?.key==='final_pair_back'&&x.active),20000);
 const start=await ev(()=>window.__game.scene.getScene('Game').children.list.find(x=>x.texture?.key==='final_pair_back').scale);
 await page.waitForTimeout(700);await shot('together-from-behind');
 assert(await page.evaluate(start=>{const s=window.__game.scene.getScene('Game'),p=s.children.list.find(x=>x.texture?.key==='final_pair_back');return p.scale<start&&p.alpha===1&&s.children.list.filter(x=>x.texture?.key==='final_portal'&&x.active).length===1},start));
 await wait(()=>window.__game.scene.getScene('Game').children.list.some(x=>x.texture?.key==='final_portal'&&x.anims?.currentAnim?.key==='final_portal:close'),7000);
 await shot('portal-closing');
 await wait(()=>window.__game.scene.getScene('Game').veilState==='done',7000);
 await page.waitForTimeout(900);await shot('to-be-continued');
 const end=await ev(()=>{const g=window.__game,s=g.scene.getScene('Game'),h=g.scene.getScene('Hud');return {
   text:h.overlay.list.map(x=>x.text).filter(Boolean),buttons:h.overlay.list.filter(x=>typeof x.activate==='function').length,
   liveFinale:s.children.list.filter(x=>x.texture?.key?.startsWith('final_')&&x.active).length,
   save:JSON.parse(localStorage.getItem('angelys-world-save-v1')),touch:h.touchUi.visible,portal:s.portal.isOpen,
   visiblePickups:[...s.hearts,...s.gems,...s.stars].filter(p=>p.sprite.active&&p.sprite.visible).length
 }});
 assert(end.text.includes('TO BE CONTINUED...'));assert.equal(end.buttons,1);assert.equal(end.liveFinale,0);assert.equal(end.touch,false);assert.equal(end.portal,false);
 assert.equal(end.save.level,21);assert.equal(end.save.finaleSeen,true);
 assert.equal(end.visiblePickups,0);
 result.checks.push(prefix+': hug, offered hand, both backs holding hands, one gate, both disappear, gate closes before TO BE CONTINUED...; one menu button');
 const pt=await ev(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return {x:r.left+640*r.width/1280,y:r.top+420*r.height/576}});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...pt,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await wait(()=>window.__game.scene.isActive('Title'));
 const chapters=await ev(()=>{const texts=[];const walk=x=>{if(x.text)texts.push(x.text);(x.list||[]).forEach(walk)};window.__game.scene.getScene('Title').children.list.forEach(walk);return texts.filter(t=>/^CHAPTER [0-9]+$/.test(t))});
 assert.equal(chapters.length,11);assert(chapters.includes('CHAPTER 11'));assert(!chapters.includes('CHAPTER 12'));assert(!chapters.includes('CHAPTER 13'));
 await shot('eleven-chapters');result.checks.push(prefix+': real BACK TO LEVELS touch returns to 11 chapters/22 levels');
 // Restart during a second finale. No queued actor, gate, wave or final screen may return.
 await fight(true);assert(await damage(160));await skip();await skip();
 await wait(()=>window.__game.scene.getScene('Game').veilState==='together'&&window.__game.scene.getScene('Hud').dialogue.active,20000);await skip();
 await wait(()=>window.__game.scene.getScene('Game').veilState==='portal_exit',20000);
 await ev(()=>window.__game.scene.getScene('Game').scene.restart({level:21}));
 await page.waitForTimeout(4500);
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').veilState),'idle');
 assert.equal(await ev(()=>window.__game.scene.getScene('Game').children.list.filter(x=>x.texture?.key?.startsWith('final_')&&x.active).length),0);
 result.checks.push(prefix+': replay and mid-departure restart remove old timers/actors without reviving the ending');
 await ev(()=>clearInterval(window.__qaShield));
 assert.deepEqual(result.errors,[]);
 fs.writeFileSync(path.join(out,prefix+'-finale-test.json'),JSON.stringify(result,null,2));
 console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(async e=>{
 const snapshot=await page?.evaluate(()=>{const s=window.__game?.scene.getScene('Game');return {veilState:s?.veilState,bossState:s?.boss?.state,hp:s?.boss?.hp,phase:s?.boss?.phase,x:s?.player?.x,vy:s?.player?.body.velocity.y,hearts:s?.player?.hearts}}).catch(()=>null);
 fs.writeFileSync(path.join(out,'finale-test-failure.json'),JSON.stringify({...result,failure:e.stack,snapshot},null,2));console.error(e,snapshot);await browser?.close();process.exitCode=1;
});
